TUTORIAL_ENGINE_VERSION = "0.1.0"
TUTORIAL_ENGINE_PORT = 4000
TUTORIAL_ENGINE_DEFAULT_NODE_TREE_NAME = 'TutorialNodeTree'
TUTORIAL_ENGINE_DEFAULT_IMAGE_SAMPLE_NAME = 'OCVLSimpleImageSampleNode'
TUTORIAL_ENGINE_DEFAULT_VIEWER_NAME = 'OCVLSimpleImageViewerNode'
TUTORIAL_ENGINE_DEFAULT_INPUT_NAME = 'image_in'
TUTORIAL_ENGINE_DEFAULT_OUTPUT_NAME = 'image_out'
